# Generated by Django 4.1 on 2023-06-10 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flying", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Travelbuddy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("img", models.ImageField(upload_to="pics")),
                ("desc", models.TextField()),
            ],
        ),
        migrations.DeleteModel(name="Peoples",),
    ]
